services:
  etl-server:
    container_name: enemyterritory
    image: oksii/etlegacy:stable
    environment:
      - 'HOSTNAME=^7RTCW ^1ET ^4Israel'
      - 'PASSWORD=${ETL_PASSWORD}'
      - 'RCONPASSWORD=${ETL_RCONPASSWORD}'
      - 'REFPASSWORD=${ETL_REFPASSWORD}'
      - 'STARTMAP=supply'
      - 'SERVERCONF=legacy6_svfps50'
      - 'MAPS=braundorf_b4:bremen_b3:decay_sw:erdenberg_t2:et_brewdog_b7:et_operation_b8:etl_adlernest_v4:etl_frostbite_v17:etl_ice_v12:etl_sp_delivery:karsiah_te2:missile_b3:supply_sp:sw_goldrush_te:te_escape2_fixed3:reactor_final'
      - 'SETTINGSURL=https://github.com/plissje/legacy-configs.git'
      - 'SETTINGSBRANCH=main'
      - 'STATS_SUBMIT=true'
      - 'STATS_API_URL_SUBMIT=https://etl-stats.maryan.io/api/submit-stats'
      - 'STATS_API_URL_MATCHID=https://etl-stats.maryan.io/api/match-manager'
      - 'STATS_API_TOKEN=${STATS_API_TOKEN}'
      - 'STATS_API_VERSION_CHECK=false'
    volumes:
      - ./maps:/maps
    ports:
      - '27960:27960/udp'
    stdin_open: true
    tty: true
    restart: unless-stopped
  etl-server-goy-6:
    container_name: enemyterritory-goy-6
    image: oksii/etlegacy:stable
    environment:
      - 'HOSTNAME=^7Only^1Frags ^7| ^36v6 ^7& ^33v3 ^7Match Server [^5ETL^7]'
      - 'MAPS=braundorf_b4:bremen_b3:decay_sw:erdenberg_t2:et_brewdog_b7:et_operation_b8:etl_adlernest_v4:etl_frostbite_v17:etl_ice_v12:etl_sp_delivery:karsiah_te2:missile_b3:supply_sp:sw_goldrush_te:te_escape2_fixed3:reactor_final'
      - 'STATS_GATHER_FEATURES=true'
      - 'STATS_SUBMIT=true'
      - 'STATS_AUTO_CONFIG_12=legacy6'
      - 'PASSWORD=${GOYPASSWORD}'
      - 'RCONPASSWORD=${GOYRCONPASSWORD}'
      - 'REFPASSWORD=${GOYREFPASSWORD}'
      - 'MAP_PORT=27970'
    volumes:
      - ./maps:/maps
    ports:
      - '27970:27970/udp'
    stdin_open: true
    tty: true
    restart: unless-stopped
  
  etl-server-goy-3:
    container_name: enemyterritory-goy-3
    image: oksii/etlegacy:stable
    environment:
      - 'HOSTNAME=^7Only^1Frags ^7| ^36v6 ^7& ^33v3 ^7Match Server [^5ETL^7]'
      - 'MAPS=braundorf_b4:bremen_b3:decay_sw:erdenberg_t2:et_brewdog_b7:et_operation_b8:etl_adlernest_v4:etl_frostbite_v17:etl_ice_v12:etl_sp_delivery:karsiah_te2:missile_b3:supply_sp:sw_goldrush_te:te_escape2_fixed3:reactor_final'
      - 'STATS_GATHER_FEATURES=true'
      - 'STATS_SUBMIT=true'
      - 'STATS_AUTO_CONFIG_6=legacy3'
      - 'PASSWORD=${GOYPASSWORD}'
      - 'RCONPASSWORD=${GOYRCONPASSWORD}'
      - 'REFPASSWORD=${GOYREFPASSWORD}'
      - 'MAP_PORT=27971'
    volumes:
      - ./maps:/maps
    ports:
      - '27971:27971/udp'
    stdin_open: true
    tty: true
    restart: unless-stopped