services:
  etl-server:
    container_name: enemyterritory
    image: oksii/etlegacy:stable
    environment:
      - 'HOSTNAME=RTCW ET Israel'
      - 'PASSWORD=${ETL_PASSWORD}'
      - 'RCONPASSWORD=${ETL_RCONPASSWORD}'
      - 'REFPASSWORD=${ETL_REFPASSWORD}'
      - 'STARTMAP=braundorf_b4'
      - 'SERVERCONF=legacy6_svfps50'
      - 'MAPS=braundorf_b4:bremen_b3:decay_sw:erdenberg_t2:et_brewdog_b7:et_operation_b8:etl_adlernest_v4:etl_frostbite_v17:etl_ice_v12:etl_sp_delivery_v5:karsiah_te2:missile_b3:supply_sp:sw_goldrush_te:te_escape2'
      - 'SETTINGSURL=https://github.com/plissje/legacy-configs.git'
      - 'SETTINGSBRANCH=main'
      - 'STATS_SUBMIT=true'
      - 'STATS_API_URL_SUBMIT=https://etl-stats.maryan.io/api/submit-stats'
      - 'STATS_API_URL_MATCHID=https://etl-stats.maryan.io/api/match-manager'
      - 'STATS_API_TOKEN=${STATS_API_TOKEN}'
      - 'STATS_API_VERSION_CHECK=false'
    volumes:
      - ./maps:/maps
    ports:
      - '27960:27960/udp'
    stdin_open: true
    tty: true
    restart: unless-stopped

  etl-server-public:
    container_name: enemyterritory-public
    image: oksii/etlegacy:stable
    environment:
      - 'HOSTNAME=Falafel & Firefights'
      - 'RCONPASSWORD=${RCONPASSWORD}'
      - 'REFPASSWORD=${REFPASSWORD}'
      - 'SCPASSWORD=${SCPASSWORD}'
      - 'PASSWORD=${PASSWORD}'
      - 'MAXCLIENTS=64'
      - 'STARTMAP=radar'
      - 'OMNIBOT=0'
      - 'SERVERCONF=public'
      - 'CF_DEFAULT_CLASS=false'
      - 'CF_TEAM_LOCK=false'
      - 'CF_TECH_PAUSE=false'
      - 'CF_GUID_BLOCKER=false'
      - 'MAPS=radar:fueldump:sw_goldrush_te:sw_oasis_b3:et_beach:etl_supply_v14:etl_frostbite_v18:etl_adlernest:braundorf_b4:etl_ice:tc_base:bremen_b3:railgun'
      - 'SETTINGSURL=https://github.com/ishaicohen/legacy-configs.git'
      - 'SETTINGSBRANCH=main'
      - 'STATS_SUBMIT=false'
      - 'MAP_PORT=27961'
    volumes:
      - ./maps:/maps
    ports:
      - '27961:27961/udp'
    stdin_open: true
    tty: true
    restart: unless-stopped
